streams:
  Gorman:
    - "rtsp://192.168.11.123:554/1/h264major/track0"
  PTZ_Thermal:
    - "rtsp://192.168.137.102:554/ONVIFMedia"
  PTZ_Visual:
    - "rtsp://192.168.137.103:554/user=admin_password=oTyLhoPM_channel=1_stream=0&onvif=0.sdp?real_stream"

api:
  listen: ":1984"  # Port for the web interface and API
  username: "admin"  # Optional: API authentication username
  password: "password"  # Optional: API authentication password

webrtc:
  candidates:
    - stun:stun.l.google.com:19302  # Example STUN server
    - stun:stun1.l.google.com:19302  # Additional STUN server for fallback
  ice_servers:
    - urls:
        - stun:stun.l.google.com:19302
        - stun:stun1.l.google.com:19302

ffmpeg:
  binary: ffmpeg  # Optional: Path to the ffmpeg binary if required for transcoding
  debug: false    # Enable debug mode for ffmpeg logging

log:
  level: info  # Logging level (debug, info, warn, error)
