streams:
  Gorman:
    - "rtsp://192.168.11.123:554/1/h264major/track0"
  PTZ_Thermal:
    - "rtsp://192.168.137.102:554/ONVIFMedia"
  PTZ_Visual:
    - "rtsp://192.168.137.103:554/user=admin_password=oTyLhoPM_channel=1_stream=0&onvif=0.sdp?real_stream"
  Front_Thermal:
    - "rtsp://192.168.137.101:554/ONVIFMedia"
api:
  listen: ":1984"  # Port for the web interface and API
#  username: "admin"  # Optional: API authentication username
#  password: "Ranger8182"  # Optional: API authentication password
  origin: "*"  # Optional: Access-Control-Allow-Origin header for the API
#  tls_listen: ":1985" # default "", enable HTTPS server
#  tls_cert: "/Users/mkulaczkowski/Aiprojects/thermaldetector/go2rtc/ssl/public.pem"
#  tls_key: "/Users/mkulaczkowski/Aiprojects/thermaldetector/go2rtc/ssl/private.pem"

webrtc:
  listen: ":8555" # external TCP/UDP port

ffmpeg:
  binary: ffmpeg  # Optional: Path to the ffmpeg binary if required for transcoding
  debug: false    # Enable debug mode for ffmpeg logging

log:
  level: debug  # Logging level (debug, info, warn, error)
  rtsp: info
  streams: info
  webrtc: info